### ISSUE TITLE
Weird -h behavioiur

### ISSUE THREAD

**Issue by tseemann** [lskatz/mashtree#40] opened 2019-08-15 22:07 UTC
0.57

```
mashtree -h

Stopped at /home/linuxbrew/.linuxbrew/bin/mashtree line 57.

echo $?
255
```

**Comment by lskatz** [comment] 2019-08-16 14:12
Can't reproduce but I am not in control of the linuxbrew version.

Line 57 of v0.57 is `die usage() if($$settings{help});` which seems appropriate.  I can't tell why the linuxbrew version wouldn't output the usage.

**Comment by tseemann** [comment] 2019-08-18 22:51
This is not a linuxbrew verison.  It was installed with `cpanm Mashtree`.

**Comment by lskatz** [comment] 2019-08-19 18:54
I added this test in `.travis.yml` : https://travis-ci.org/lskatz/mashtree/jobs/573972927#L1428

Is the issue more about the exit code?  If so, then I agree that it is running as expected.  I placed the usage statement in a `die()`.

**Comment by mihkelvaher** [comment] 2019-09-24 12:51
If the problem is showing the line number, then it can be resolved by adding a `\n` to the end of the usage string. This suppresses `die()` line number printing.

**Comment by lskatz** [comment] 2019-09-24 16:59
I went ahead and just changed the exit code in 9476c220d787c14ab10e40e4254e061cdb135eb8

**Closed by lskatz** 2019-09-24 16:59 UTC
